export const USER_CARDS_RETRIEVED ="USER_CARDS_RETRIEVED";
export const CARDS_RETRIEVED_ERROR = "CARDS_RETRIEVED_ERROR";
export const DEALER_CARDS_RETRIEVED = "DEALER_CARDS_RETRIEVED";
export const DECK_ID = "DECK_ID";
export const STORE_RESULTS = "STORE_RESULTS"

export default {
  CARDS_RETRIEVED_ERROR,
  USER_CARDS_RETRIEVED,
  DEALER_CARDS_RETRIEVED,
  DECK_ID,
  STORE_RESULTS
};
